const UPDATE_MESSAGE = 'UPDATE_MESSAGE'
const USER_LOGIN = 'USER_LOGIN'
const FETCH_PRODUCTS = 'FETCH_PRODUCTS'
const DELETE_PRODUCT = 'DELETE_PRODUCT'
const FETCH_PRODUCT = 'FETCH_PRODUCT'

export { UPDATE_MESSAGE , USER_LOGIN , FETCH_PRODUCTS , DELETE_PRODUCT , FETCH_PRODUCT }